### ISSUE TITLE
question, I don't understand how RoCE works and I haven't had much luck 

### ISSUE THREAD

**Issue by cloudkitsch** [jgunthorpe/python-rdma#14]
can you point me to the right documentation if this available on linux? I have two emulex 10gbe cards that I have weird behavior with, so I'd like to try something else? I don't really understand what converged ethernet is, I should probably look that up first

**Comment by cloudkitsch** [comment]
sigh, https://en.wikipedia.org/wiki/RDMA_over_Converged_Ethernet#Criticism

**Comment by jgunthorpe** [comment]
Python RDMA does not really support RoCEE. It lacks the RDMA-CM interface which is mandatory.
