### ISSUE TITLE
ibsim functionality 

### ISSUE THREAD

**Issue by ChristianKniep** [jgunthorpe/python-rdma#9]
Hey there,

I am revisiting my IB past and currently checking out your wonderful library.
On a host with a real card this works without a problem:
```
python -c "import rdma;print rdma.get_devices()"
{'mlx4_0': <rdma.devices.RDMADevice object for mlx4_0 at 0x2968e10>}
```

But if I run it on a node using ibsim, it fails:
```
# echo $LD_PRELOAD
/usr/lib64/umad2sim/libumad2sim.so
# python -c "import rdma;print rdma.get_devices()"
{}
```
I used your ibsim repo (0.5) and the upstream of fedora20 (0.6).

What do I miss? The branch 'sim' seems to be pretty old.

Cheers
Christian

**Comment by jgunthorpe** [comment]
This doc probably explains the missing bits:

https://github.com/jgunthorpe/python-rdma/blob/sim/doc/sim.rst

No preload library is needed.

**Comment by ChristianKniep** [comment]
Oh, sorry... I didn't catch this document. Will try it out.
Thanks!
